services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: hamzury
      POSTGRES_PASSWORD: hamzury
      POSTGRES_DB: hamzury
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
